# Generated by Django 5.1.3 on 2024-11-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_allowed_notification",
            field=models.BooleanField(default=False),
        ),
    ]
