# Generated by Django 5.1.3 on 2024-12-09 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="support",
            name="repository",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.repository",
            ),
        ),
    ]
